name: ramboo-engineering

# Region - change as needed
region: sgp

# Backend API Service
services:
  - name: api
    dockerfile_path: backend/Dockerfile
    source_dir: backend
    http_port: 3001
    instance_size_slug: basic-xxs
    instance_count: 1
    health_check:
      http_path: /api/health
      initial_delay_seconds: 10
      period_seconds: 30
    routes:
      - path: /api
    envs:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        type: SECRET
        value: ${JWT_SECRET}
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${db.DATABASE_URL}
      - key: CORS_ORIGIN
        value: ${frontend.PUBLIC_URL}

# Frontend Static Site
static_sites:
  - name: frontend
    dockerfile_path: frontend/Dockerfile
    source_dir: frontend
    build_command: npm run build
    output_dir: dist
    routes:
      - path: /
    envs:
      - key: VITE_API_URL
        value: ${api.PUBLIC_URL}/api

# Managed PostgreSQL Database
databases:
  - name: db
    engine: PG
    version: "16"
    size: db-s-dev-database
    num_nodes: 1
