name: ramboo-garage
region: sgp

services:
  - name: api
    github:
      repo: shubbatt/garge
      branch: main
      deploy_on_push: true
    source_dir: backend
    dockerfile_path: backend/Dockerfile
    http_port: 3001
    instance_size_slug: basic-xxs
    instance_count: 1
    routes:
      - path: /api
    envs:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        type: SECRET
        value: EV[1:your-secret-here]
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${db.DATABASE_URL}

static_sites:
  - name: frontend
    github:
      repo: shubbatt/garge
      branch: main
      deploy_on_push: true
    source_dir: frontend
    build_command: npm ci && npm run build
    output_dir: dist
    routes:
      - path: /
    envs:
      - key: VITE_API_URL
        value: ${api.PUBLIC_URL}

databases:
  - name: db
    engine: PG
    version: "16"
    production: false
    cluster_name: ramboo-db
